#***** CLOCK *****
set_property PACKAGE_PIN T5 [get_ports CLK_50M]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_50M]

#//**** BUTTONS ****//
set_property PACKAGE_PIN V9 [get_ports BT_RST]
set_property IOSTANDARD LVCMOS33 [get_ports BT_RST]
set_property PULLUP true [get_ports BT_RST]

set_property PACKAGE_PIN T9 [get_ports BT_DRV]
set_property IOSTANDARD LVCMOS33 [get_ports BT_DRV]
set_property PULLUP true [get_ports BT_DRV]

set_property PACKAGE_PIN T8 [get_ports BT_NMI]
set_property IOSTANDARD LVCMOS33 [get_ports BT_NMI]
set_property PULLUP true [get_ports BT_NMI]

#//PS2 KEYBOARD
set_property PACKAGE_PIN K1 [get_ports ps2_clk_io]
set_property PACKAGE_PIN L4 [get_ports ps2_data_io]
#set_property PACKAGE_PIN L3 [get_ports ps2_pin2_io]
#set_property PACKAGE_PIN L5 [get_ports ps2_pin6_io]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_clk_io]
#set_property DRIVE 16 [get_ports ps2_clk_io]
set_property PULLUP true [get_ports ps2_clk_io]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_data_io]
#set_property DRIVE 16 [get_ports ps2_data_io]
set_property PULLUP true [get_ports ps2_data_io]
#set_property IOSTANDARD LVCMOS33 [get_ports ps2_pin2_io]
#set_property DRIVE 16 [get_ports ps2_pin2_io]
#set_property PULLUP true [get_ports ps2_pin2_io]
#set_property IOSTANDARD LVCMOS33 [get_ports ps2_pin6_io]
#set_property DRIVE 16 [get_ports ps2_pin6_io]
#set_property PULLUP true [get_ports ps2_pin6_io]
set_property OFFCHIP_TERM NONE [get_ports ps2_clk_io]
set_property OFFCHIP_TERM NONE [get_ports ps2_data_io]
#set_property OFFCHIP_TERM NONE [get_ports ps2_pin2_io]
#set_property OFFCHIP_TERM NONE [get_ports ps2_pin6_io]

#Matrix Keyboard
set_property PACKAGE_PIN T18 [get_ports {keyb_col_i[5]}]
set_property PACKAGE_PIN R17 [get_ports {keyb_col_i[6]}]
set_property PACKAGE_PIN U6 [get_ports {keyb_col_i[4]}]
set_property PACKAGE_PIN V7 [get_ports {keyb_col_i[3]}]
set_property PACKAGE_PIN T6 [get_ports {keyb_col_i[2]}]
set_property PACKAGE_PIN R7 [get_ports {keyb_col_i[1]}]
set_property PACKAGE_PIN R8 [get_ports {keyb_col_i[0]}]
set_property PACKAGE_PIN N16 [get_ports {keyb_row_o[3]}]
set_property PACKAGE_PIN M13 [get_ports {keyb_row_o[2]}]
set_property PACKAGE_PIN M16 [get_ports {keyb_row_o[1]}]
set_property PACKAGE_PIN K16 [get_ports {keyb_row_o[4]}]
set_property PACKAGE_PIN K15 [get_ports {keyb_row_o[5]}]
set_property PACKAGE_PIN J14 [get_ports {keyb_row_o[0]}]
set_property PACKAGE_PIN K13 [get_ports {keyb_row_o[6]}]
set_property PACKAGE_PIN J15 [get_ports {keyb_row_o[7]}]
#
#
set_property IOSTANDARD LVTTL [get_ports {keyb_col_i[6]}]
set_property IOSTANDARD LVTTL [get_ports {keyb_col_i[5]}]
set_property IOSTANDARD LVTTL [get_ports {keyb_col_i[4]}]
set_property IOSTANDARD LVTTL [get_ports {keyb_col_i[3]}]
set_property IOSTANDARD LVTTL [get_ports {keyb_col_i[2]}]
set_property IOSTANDARD LVTTL [get_ports {keyb_col_i[1]}]
set_property IOSTANDARD LVTTL [get_ports {keyb_col_i[0]}]
set_property PULLUP true [get_ports {keyb_col_i[0]}]
set_property PULLUP true [get_ports {keyb_col_i[1]}]
set_property PULLUP true [get_ports {keyb_col_i[2]}]
set_property PULLUP true [get_ports {keyb_col_i[3]}]
set_property PULLUP true [get_ports {keyb_col_i[4]}]
set_property PULLUP true [get_ports {keyb_col_i[5]}]
set_property PULLUP true [get_ports {keyb_col_i[6]}]

set_property IOSTANDARD LVTTL [get_ports {keyb_row_o[7]}]
set_property IOSTANDARD LVTTL [get_ports {keyb_row_o[6]}]
set_property IOSTANDARD LVTTL [get_ports {keyb_row_o[5]}]
set_property IOSTANDARD LVTTL [get_ports {keyb_row_o[4]}]
set_property IOSTANDARD LVTTL [get_ports {keyb_row_o[3]}]
set_property IOSTANDARD LVTTL [get_ports {keyb_row_o[2]}]
set_property IOSTANDARD LVTTL [get_ports {keyb_row_o[1]}]
set_property IOSTANDARD LVTTL [get_ports {keyb_row_o[0]}]
set_property DRIVE 4 [get_ports {keyb_row_o[7]}]
set_property DRIVE 4 [get_ports {keyb_row_o[6]}]
set_property DRIVE 4 [get_ports {keyb_row_o[5]}]
set_property DRIVE 4 [get_ports {keyb_row_o[4]}]
set_property DRIVE 4 [get_ports {keyb_row_o[3]}]
set_property DRIVE 4 [get_ports {keyb_row_o[2]}]
set_property DRIVE 4 [get_ports {keyb_row_o[1]}]
set_property DRIVE 4 [get_ports {keyb_row_o[0]}]
set_property PULLUP true [get_ports {keyb_row_o[7]}]
set_property PULLUP true [get_ports {keyb_row_o[6]}]
set_property PULLUP true [get_ports {keyb_row_o[5]}]
set_property PULLUP true [get_ports {keyb_row_o[4]}]
set_property PULLUP true [get_ports {keyb_row_o[3]}]
set_property PULLUP true [get_ports {keyb_row_o[2]}]
set_property PULLUP true [get_ports {keyb_row_o[1]}]
set_property PULLUP true [get_ports {keyb_row_o[0]}]

#JOYSTICKS
set_property PACKAGE_PIN T13 [get_ports joyp1_i]
set_property PACKAGE_PIN R12 [get_ports joyp2_i]
set_property PACKAGE_PIN V16 [get_ports joyp3_i]
set_property PACKAGE_PIN U17 [get_ports joyp4_i]
set_property PACKAGE_PIN V15 [get_ports joyp6_i]
set_property PACKAGE_PIN R13 [get_ports joyp7_o]
set_property PACKAGE_PIN V17 [get_ports joyp9_i]
set_property PACKAGE_PIN U14 [get_ports joysel_o]
set_property IOSTANDARD LVTTL [get_ports joyp1_i]
set_property IOSTANDARD LVTTL [get_ports joyp2_i]
set_property IOSTANDARD LVTTL [get_ports joyp3_i]
set_property IOSTANDARD LVTTL [get_ports joyp4_i]
set_property IOSTANDARD LVTTL [get_ports joyp6_i]
set_property IOSTANDARD LVTTL [get_ports joyp7_o]
set_property DRIVE 4 [get_ports joyp7_o]
set_property IOSTANDARD LVTTL [get_ports joyp9_i]
set_property IOSTANDARD LVTTL [get_ports joysel_o]
set_property DRIVE 4 [get_ports joysel_o]



#***** VIDEO *****

set_property PACKAGE_PIN B13 [get_ports VGA_VS]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_VS]

set_property PACKAGE_PIN A13 [get_ports VGA_HS]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_HS]

set_property PACKAGE_PIN J5 [get_ports {VGA_R[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[0]}]
set_property PACKAGE_PIN K5 [get_ports {VGA_R[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[1]}]
set_property PACKAGE_PIN K3 [get_ports {VGA_R[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[2]}]

set_property PACKAGE_PIN H4 [get_ports {VGA_G[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[0]}]
set_property PACKAGE_PIN J4 [get_ports {VGA_G[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[1]}]
set_property PACKAGE_PIN J3 [get_ports {VGA_G[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[2]}]

set_property PACKAGE_PIN A3 [get_ports {VGA_B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[0]}]
set_property PACKAGE_PIN C2 [get_ports {VGA_B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[1]}]
set_property PACKAGE_PIN G3 [get_ports {VGA_B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[2]}]


#***** MEMORY *****

set_property PACKAGE_PIN C1 [get_ports {RAM_A[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[0]}]
set_property PACKAGE_PIN D2 [get_ports {RAM_A[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[1]}]
set_property PACKAGE_PIN E1 [get_ports {RAM_A[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[2]}]
set_property PACKAGE_PIN F3 [get_ports {RAM_A[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[3]}]
set_property PACKAGE_PIN E2 [get_ports {RAM_A[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[4]}]
set_property PACKAGE_PIN G4 [get_ports {RAM_A[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[5]}]
set_property PACKAGE_PIN J2 [get_ports {RAM_A[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[6]}]
set_property PACKAGE_PIN N2 [get_ports {RAM_A[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[7]}]
set_property PACKAGE_PIN T3 [get_ports {RAM_A[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[8]}]
set_property PACKAGE_PIN R3 [get_ports {RAM_A[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[9]}]
set_property PACKAGE_PIN P4 [get_ports {RAM_A[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[10]}]
set_property PACKAGE_PIN N4 [get_ports {RAM_A[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[11]}]
set_property PACKAGE_PIN P5 [get_ports {RAM_A[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[12]}]
set_property PACKAGE_PIN P3 [get_ports {RAM_A[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[13]}]
set_property PACKAGE_PIN R1 [get_ports {RAM_A[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[14]}]
set_property PACKAGE_PIN T1 [get_ports {RAM_A[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[15]}]
set_property PACKAGE_PIN R2 [get_ports {RAM_A[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[16]}]
set_property PACKAGE_PIN P2 [get_ports {RAM_A[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[17]}]
set_property PACKAGE_PIN V2 [get_ports {RAM_A[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[18]}]
set_property PACKAGE_PIN R5 [get_ports {RAM_A[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[19]}]

set_property DRIVE 8 [get_ports {RAM_A[0]}]
set_property DRIVE 8 [get_ports {RAM_A[1]}]
set_property DRIVE 8 [get_ports {RAM_A[2]}]
set_property DRIVE 8 [get_ports {RAM_A[3]}]
set_property DRIVE 8 [get_ports {RAM_A[4]}]
set_property DRIVE 8 [get_ports {RAM_A[5]}]
set_property DRIVE 8 [get_ports {RAM_A[6]}]
set_property DRIVE 8 [get_ports {RAM_A[7]}]
set_property DRIVE 8 [get_ports {RAM_A[8]}]
set_property DRIVE 8 [get_ports {RAM_A[9]}]
set_property DRIVE 8 [get_ports {RAM_A[10]}]
set_property DRIVE 8 [get_ports {RAM_A[11]}]
set_property DRIVE 8 [get_ports {RAM_A[12]}]
set_property DRIVE 8 [get_ports {RAM_A[13]}]
set_property DRIVE 8 [get_ports {RAM_A[14]}]
set_property DRIVE 8 [get_ports {RAM_A[15]}]
set_property DRIVE 8 [get_ports {RAM_A[16]}]
set_property DRIVE 8 [get_ports {RAM_A[17]}]
set_property DRIVE 8 [get_ports {RAM_A[18]}]
set_property DRIVE 8 [get_ports {RAM_A[19]}]

set_property SLEW FAST [get_ports {RAM_A[0]}]
set_property SLEW FAST [get_ports {RAM_A[1]}]
set_property SLEW FAST [get_ports {RAM_A[2]}]
set_property SLEW FAST [get_ports {RAM_A[3]}]
set_property SLEW FAST [get_ports {RAM_A[4]}]
set_property SLEW FAST [get_ports {RAM_A[5]}]
set_property SLEW FAST [get_ports {RAM_A[6]}]
set_property SLEW FAST [get_ports {RAM_A[7]}]
set_property SLEW FAST [get_ports {RAM_A[8]}]
set_property SLEW FAST [get_ports {RAM_A[9]}]
set_property SLEW FAST [get_ports {RAM_A[10]}]
set_property SLEW FAST [get_ports {RAM_A[11]}]
set_property SLEW FAST [get_ports {RAM_A[12]}]
set_property SLEW FAST [get_ports {RAM_A[13]}]
set_property SLEW FAST [get_ports {RAM_A[14]}]
set_property SLEW FAST [get_ports {RAM_A[15]}]
set_property SLEW FAST [get_ports {RAM_A[16]}]
set_property SLEW FAST [get_ports {RAM_A[17]}]
set_property SLEW FAST [get_ports {RAM_A[18]}]
set_property SLEW FAST [get_ports {RAM_A[19]}]

set_property PACKAGE_PIN G2 [get_ports {RAM_D[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_D[0]}]
set_property PACKAGE_PIN G1 [get_ports {RAM_D[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_D[1]}]
set_property PACKAGE_PIN H2 [get_ports {RAM_D[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_D[2]}]
set_property PACKAGE_PIN H1 [get_ports {RAM_D[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_D[3]}]
set_property PACKAGE_PIN U1 [get_ports {RAM_D[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_D[4]}]
set_property PACKAGE_PIN V1 [get_ports {RAM_D[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_D[5]}]
set_property PACKAGE_PIN U2 [get_ports {RAM_D[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_D[6]}]
set_property PACKAGE_PIN M3 [get_ports {RAM_D[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_D[7]}]
set_property PACKAGE_PIN D3 [get_ports {RAM_D[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_D[8]}]
set_property PACKAGE_PIN A5 [get_ports {RAM_D[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_D[9]}]
set_property PACKAGE_PIN D4 [get_ports {RAM_D[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_D[10]}]
set_property PACKAGE_PIN A6 [get_ports {RAM_D[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_D[11]}]
set_property PACKAGE_PIN U9 [get_ports {RAM_D[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_D[12]}]
set_property PACKAGE_PIN V6 [get_ports {RAM_D[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_D[13]}]
set_property PACKAGE_PIN U7 [get_ports {RAM_D[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_D[14]}]
set_property PACKAGE_PIN U3 [get_ports {RAM_D[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_D[15]}]

set_property DRIVE 8 [get_ports {RAM_D[0]}]
set_property DRIVE 8 [get_ports {RAM_D[1]}]
set_property DRIVE 8 [get_ports {RAM_D[2]}]
set_property DRIVE 8 [get_ports {RAM_D[3]}]
set_property DRIVE 8 [get_ports {RAM_D[4]}]
set_property DRIVE 8 [get_ports {RAM_D[5]}]
set_property DRIVE 8 [get_ports {RAM_D[6]}]
set_property DRIVE 8 [get_ports {RAM_D[7]}]
set_property DRIVE 8 [get_ports {RAM_D[8]}]
set_property DRIVE 8 [get_ports {RAM_D[9]}]
set_property DRIVE 8 [get_ports {RAM_D[10]}]
set_property DRIVE 8 [get_ports {RAM_D[11]}]
set_property DRIVE 8 [get_ports {RAM_D[12]}]
set_property DRIVE 8 [get_ports {RAM_D[13]}]
set_property DRIVE 8 [get_ports {RAM_D[14]}]
set_property DRIVE 8 [get_ports {RAM_D[15]}]

set_property SLEW FAST [get_ports {RAM_D[0]}]
set_property SLEW FAST [get_ports {RAM_D[1]}]
set_property SLEW FAST [get_ports {RAM_D[2]}]
set_property SLEW FAST [get_ports {RAM_D[3]}]
set_property SLEW FAST [get_ports {RAM_D[4]}]
set_property SLEW FAST [get_ports {RAM_D[5]}]
set_property SLEW FAST [get_ports {RAM_D[6]}]
set_property SLEW FAST [get_ports {RAM_D[7]}]
set_property SLEW FAST [get_ports {RAM_D[8]}]
set_property SLEW FAST [get_ports {RAM_D[9]}]
set_property SLEW FAST [get_ports {RAM_D[10]}]
set_property SLEW FAST [get_ports {RAM_D[11]}]
set_property SLEW FAST [get_ports {RAM_D[12]}]
set_property SLEW FAST [get_ports {RAM_D[13]}]
set_property SLEW FAST [get_ports {RAM_D[14]}]
set_property SLEW FAST [get_ports {RAM_D[15]}]

set_property PULLUP true [get_ports {RAM_D[0]}]
set_property PULLUP true [get_ports {RAM_D[1]}]
set_property PULLUP true [get_ports {RAM_D[2]}]
set_property PULLUP true [get_ports {RAM_D[3]}]
set_property PULLUP true [get_ports {RAM_D[4]}]
set_property PULLUP true [get_ports {RAM_D[5]}]
set_property PULLUP true [get_ports {RAM_D[6]}]
set_property PULLUP true [get_ports {RAM_D[7]}]
set_property PULLUP true [get_ports {RAM_D[8]}]
set_property PULLUP true [get_ports {RAM_D[9]}]
set_property PULLUP true [get_ports {RAM_D[10]}]
set_property PULLUP true [get_ports {RAM_D[11]}]
set_property PULLUP true [get_ports {RAM_D[12]}]
set_property PULLUP true [get_ports {RAM_D[13]}]
set_property PULLUP true [get_ports {RAM_D[14]}]
set_property PULLUP true [get_ports {RAM_D[15]}]

set_property PACKAGE_PIN F5 [get_ports RAM_LB]
set_property IOSTANDARD LVCMOS33 [get_ports RAM_LB]
set_property PACKAGE_PIN E3 [get_ports RAM_UB]
set_property IOSTANDARD LVCMOS33 [get_ports RAM_UB]

set_property DRIVE 8 [get_ports {RAM_LB}]
set_property DRIVE 8 [get_ports {RAM_UB}]
set_property SLEW FAST [get_ports {RAM_LB}]
set_property SLEW FAST [get_ports {RAM_UB}]

set_property PACKAGE_PIN F1 [get_ports RAM_CS]
set_property IOSTANDARD LVCMOS33 [get_ports RAM_CS]
set_property PACKAGE_PIN F4 [get_ports RAM_OE]
set_property IOSTANDARD LVCMOS33 [get_ports RAM_OE]
set_property PACKAGE_PIN M4 [get_ports RAM_WE]
set_property IOSTANDARD LVCMOS33 [get_ports RAM_WE]

set_property DRIVE 8 [get_ports {RAM_CS}]
set_property SLEW FAST [get_ports {RAM_CS}]
set_property DRIVE 8 [get_ports {RAM_OE}]
set_property SLEW FAST [get_ports {RAM_OE}]
set_property DRIVE 8 [get_ports {RAM_WE}]
set_property SLEW FAST [get_ports {RAM_WE}]

#// SD CARD //
set_property PACKAGE_PIN N1 [get_ports SD_CS]
set_property PACKAGE_PIN K2 [get_ports SD_CS1]
set_property PACKAGE_PIN L1 [get_ports SD_MISO]
set_property PACKAGE_PIN M2 [get_ports SD_MOSI]
set_property PACKAGE_PIN M1 [get_ports SD_CLK]

set_property IOSTANDARD LVTTL [get_ports SD_CS]
set_property DRIVE 4 [get_ports SD_CS]
set_property IOSTANDARD LVTTL [get_ports SD_CS1]
set_property DRIVE 4 [get_ports SD_CS1]
set_property IOSTANDARD LVTTL [get_ports SD_MISO]
set_property PULLUP true [get_ports SD_MISO]
set_property IOSTANDARD LVTTL [get_ports SD_MOSI]
set_property DRIVE 4 [get_ports SD_MOSI]
set_property IOSTANDARD LVTTL [get_ports SD_CLK]
set_property DRIVE 4 [get_ports SD_CLK]

##AUDIO

set_property PACKAGE_PIN B4 [get_ports audioext_l_o]
set_property PACKAGE_PIN A4 [get_ports audioext_r_o]
set_property OFFCHIP_TERM NONE [get_ports audioext_l_o]
set_property OFFCHIP_TERM NONE [get_ports audioext_r_o]
set_property DRIVE 16 [get_ports audioext_l_o]
set_property DRIVE 16 [get_ports audioext_r_o]
set_property IOSTANDARD LVCMOS33 [get_ports audioext_l_o]
set_property IOSTANDARD LVCMOS33 [get_ports audioext_r_o]

#set_property PACKAGE_PIN U16 [get_ports audioint_o]
#set_property IOSTANDARD LVCMOS33 [get_ports audioint_o]
#set_property DRIVE 8 [get_ports audioint_o]
#set_property SLEW SLOW [get_ports audioint_o]

#Expansion Bus
set_property PACKAGE_PIN A18 [get_ports iec_atn_o]
set_property PACKAGE_PIN C5 [get_ports iec_clk_io]
set_property PACKAGE_PIN A10 [get_ports iec_data_io]


set_property IOSTANDARD LVCMOS33 [get_ports iec_atn_o]
set_property DRIVE 4 [get_ports iec_atn_o]
set_property PULLUP true [get_ports iec_atn_o]
set_property IOSTANDARD LVCMOS33 [get_ports iec_clk_io]
set_property DRIVE 4 [get_ports iec_clk_io]
set_property PULLUP true [get_ports iec_clk_io]
set_property IOSTANDARD LVCMOS33 [get_ports iec_data_io]
set_property DRIVE 4 [get_ports iec_data_io]
set_property PULLUP true [get_ports iec_data_io]

set_property PACKAGE_PIN E7 [get_ports bus_y_o]
set_property IOSTANDARD LVCMOS33 [get_ports bus_y_o]
set_property DRIVE 4 [get_ports bus_y_o]
set_property PULLUP true [get_ports bus_y_o]

set_property IOSTANDARD LVCMOS33 [get_ports bus_busack_n_o]
set_property DRIVE 4 [get_ports bus_busack_n_o]
set_property PULLUP true [get_ports bus_busack_n_o]
set_property PACKAGE_PIN P15 [get_ports bus_busack_n_o]

#set_property PACKAGE_PIN C17 [get_ports bus_halt_n_o]
#set_property IOSTANDARD LVCMOS33 [get_ports bus_halt_n_o]
#set_property DRIVE 4 [get_ports bus_halt_n_o]
#set_property PULLUP true [get_ports bus_halt_n_o]

