#***** CLOCK *****
set_property PACKAGE_PIN L17[get_ports CLK_12M]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_12M]

#//**** BUTTONS ****//
set_property PACKAGE_PIN A18 [get_ports BT_RST]
set_property IOSTANDARD LVCMOS33 [get_ports BT_RST]
set_property PULLUP true [get_ports BT_RST]

set_property PACKAGE_PIN B18 [get_ports BT_DRV]
set_property IOSTANDARD LVCMOS33 [get_ports BT_DRV]
set_property PULLUP true [get_ports BT_DRV]

#set_property PACKAGE_PIN T8 [get_ports BT_NMI]
#set_property IOSTANDARD LVCMOS33 [get_ports BT_NMI]
#set_property PULLUP true [get_ports BT_NMI]

#//KEYBOARD
set_property PACKAGE_PIN N1 [get_ports ps2_clk_io]
set_property PACKAGE_PIN M2 [get_ports ps2_data_io]
#set_property PACKAGE_PIN L3 [get_ports ps2_pin2_io]
#set_property PACKAGE_PIN L5 [get_ports ps2_pin6_io]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_clk_io]
#set_property DRIVE 16 [get_ports ps2_clk_io]
set_property PULLUP true [get_ports ps2_clk_io]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_data_io]
#set_property DRIVE 16 [get_ports ps2_data_io]
set_property PULLUP true [get_ports ps2_data_io]
#set_property IOSTANDARD LVCMOS33 [get_ports ps2_pin2_io]
#set_property DRIVE 16 [get_ports ps2_pin2_io]
#set_property PULLUP true [get_ports ps2_pin2_io]
#set_property IOSTANDARD LVCMOS33 [get_ports ps2_pin6_io]
#set_property DRIVE 16 [get_ports ps2_pin6_io]
#set_property PULLUP true [get_ports ps2_pin6_io]
set_property OFFCHIP_TERM NONE [get_ports ps2_clk_io]
set_property OFFCHIP_TERM NONE [get_ports ps2_data_io]
#set_property OFFCHIP_TERM NONE [get_ports ps2_pin2_io]
#set_property OFFCHIP_TERM NONE [get_ports ps2_pin6_io]



#***** VIDEO *****

set_property PACKAGE_PIN P1 [get_ports VGA_VS]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_VS]

set_property PACKAGE_PIN N2 [get_ports VGA_HS]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_HS]

set_property PACKAGE_PIN J1 [get_ports {VGA_R[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[0]}]
set_property PACKAGE_PIN K2 [get_ports {VGA_R[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[1]}]
set_property PACKAGE_PIN L1 [get_ports {VGA_R[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[2]}]
set_property PACKAGE_PIN L2 [get_ports {VGA_R[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[3]}]

set_property PACKAGE_PIN A15 [get_ports {VGA_G[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[0]}]
set_property PACKAGE_PIN B15 [get_ports {VGA_G[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[1]}]
set_property PACKAGE_PIN A14 [get_ports {VGA_G[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[2]}]
set_property PACKAGE_PIN J3 [get_ports {VGA_G[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[3]}]

set_property PACKAGE_PIN A16 [get_ports {VGA_B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[0]}]
set_property PACKAGE_PIN K3 [get_ports {VGA_B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[1]}]
set_property PACKAGE_PIN C15 [get_ports {VGA_B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[2]}]
set_property PACKAGE_PIN H1 [get_ports {VGA_B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[3]}]


#***** MEMORY *****

set_property PACKAGE_PIN M18 [get_ports {RAM_A[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[0]}]
set_property PACKAGE_PIN M19 [get_ports {RAM_A[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[1]}]
set_property PACKAGE_PIN K17 [get_ports {RAM_A[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[2]}]
set_property PACKAGE_PIN N17 [get_ports {RAM_A[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[3]}]
set_property PACKAGE_PIN P17 [get_ports {RAM_A[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[4]}]
set_property PACKAGE_PIN P18 [get_ports {RAM_A[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[5]}]
set_property PACKAGE_PIN R18 [get_ports {RAM_A[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[6]}]
set_property PACKAGE_PIN N2 [get_ports {RAM_A[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[7]}]
set_property PACKAGE_PIN W19 [get_ports {RAM_A[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[8]}]
set_property PACKAGE_PIN U19 [get_ports {RAM_A[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[9]}]
set_property PACKAGE_PIN V19 [get_ports {RAM_A[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[10]}]
set_property PACKAGE_PIN W18 [get_ports {RAM_A[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[11]}]
set_property PACKAGE_PIN T17 [get_ports {RAM_A[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[12]}]
set_property PACKAGE_PIN T18 [get_ports {RAM_A[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[13]}]
set_property PACKAGE_PIN U17 [get_ports {RAM_A[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[14]}]
set_property PACKAGE_PIN U18 [get_ports {RAM_A[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[15]}]
set_property PACKAGE_PIN V16 [get_ports {RAM_A[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[16]}]
set_property PACKAGE_PIN W16 [get_ports {RAM_A[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[17]}]
set_property PACKAGE_PIN W17 [get_ports {RAM_A[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[18]}]
#set_property PACKAGE_PIN V15 [get_ports {RAM_A[19]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {RAM_A[19]}]

set_property DRIVE 8 [get_ports {RAM_A[0]}]
set_property DRIVE 8 [get_ports {RAM_A[1]}]
set_property DRIVE 8 [get_ports {RAM_A[2]}]
set_property DRIVE 8 [get_ports {RAM_A[3]}]
set_property DRIVE 8 [get_ports {RAM_A[4]}]
set_property DRIVE 8 [get_ports {RAM_A[5]}]
set_property DRIVE 8 [get_ports {RAM_A[6]}]
set_property DRIVE 8 [get_ports {RAM_A[7]}]
set_property DRIVE 8 [get_ports {RAM_A[8]}]
set_property DRIVE 8 [get_ports {RAM_A[9]}]
set_property DRIVE 8 [get_ports {RAM_A[10]}]
set_property DRIVE 8 [get_ports {RAM_A[11]}]
set_property DRIVE 8 [get_ports {RAM_A[12]}]
set_property DRIVE 8 [get_ports {RAM_A[13]}]
set_property DRIVE 8 [get_ports {RAM_A[14]}]
set_property DRIVE 8 [get_ports {RAM_A[15]}]
set_property DRIVE 8 [get_ports {RAM_A[16]}]
set_property DRIVE 8 [get_ports {RAM_A[17]}]
set_property DRIVE 8 [get_ports {RAM_A[18]}]
#set_property DRIVE 8 [get_ports {RAM_A[19]}]

set_property SLEW FAST [get_ports {RAM_A[0]}]
set_property SLEW FAST [get_ports {RAM_A[1]}]
set_property SLEW FAST [get_ports {RAM_A[2]}]
set_property SLEW FAST [get_ports {RAM_A[3]}]
set_property SLEW FAST [get_ports {RAM_A[4]}]
set_property SLEW FAST [get_ports {RAM_A[5]}]
set_property SLEW FAST [get_ports {RAM_A[6]}]
set_property SLEW FAST [get_ports {RAM_A[7]}]
set_property SLEW FAST [get_ports {RAM_A[8]}]
set_property SLEW FAST [get_ports {RAM_A[9]}]
set_property SLEW FAST [get_ports {RAM_A[10]}]
set_property SLEW FAST [get_ports {RAM_A[11]}]
set_property SLEW FAST [get_ports {RAM_A[12]}]
set_property SLEW FAST [get_ports {RAM_A[13]}]
set_property SLEW FAST [get_ports {RAM_A[14]}]
set_property SLEW FAST [get_ports {RAM_A[15]}]
set_property SLEW FAST [get_ports {RAM_A[16]}]
set_property SLEW FAST [get_ports {RAM_A[17]}]
set_property SLEW FAST [get_ports {RAM_A[18]}]
#set_property SLEW FAST [get_ports {RAM_A[19]}]

set_property PACKAGE_PIN W15 [get_ports {RAM_D[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_D[0]}]
set_property PACKAGE_PIN W13 [get_ports {RAM_D[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_D[1]}]
set_property PACKAGE_PIN W14 [get_ports {RAM_D[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_D[2]}]
set_property PACKAGE_PIN U15 [get_ports {RAM_D[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_D[3]}]
set_property PACKAGE_PIN U16 [get_ports {RAM_D[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_D[4]}]
set_property PACKAGE_PIN V13 [get_ports {RAM_D[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_D[5]}]
set_property PACKAGE_PIN V14 [get_ports {RAM_D[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_D[6]}]
set_property PACKAGE_PIN U14 [get_ports {RAM_D[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RAM_D[7]}]
#set_property PACKAGE_PIN D3 [get_ports {RAM_D[8]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {RAM_D[8]}]
#set_property PACKAGE_PIN A5 [get_ports {RAM_D[9]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {RAM_D[9]}]
#set_property PACKAGE_PIN D4 [get_ports {RAM_D[10]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {RAM_D[10]}]
#set_property PACKAGE_PIN A6 [get_ports {RAM_D[11]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {RAM_D[11]}]
#set_property PACKAGE_PIN U9 [get_ports {RAM_D[12]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {RAM_D[12]}]
#set_property PACKAGE_PIN V6 [get_ports {RAM_D[13]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {RAM_D[13]}]
#set_property PACKAGE_PIN U7 [get_ports {RAM_D[14]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {RAM_D[14]}]
#set_property PACKAGE_PIN U3 [get_ports {RAM_D[15]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {RAM_D[15]}]

set_property DRIVE 8 [get_ports {RAM_D[0]}]
set_property DRIVE 8 [get_ports {RAM_D[1]}]
set_property DRIVE 8 [get_ports {RAM_D[2]}]
set_property DRIVE 8 [get_ports {RAM_D[3]}]
set_property DRIVE 8 [get_ports {RAM_D[4]}]
set_property DRIVE 8 [get_ports {RAM_D[5]}]
set_property DRIVE 8 [get_ports {RAM_D[6]}]
set_property DRIVE 8 [get_ports {RAM_D[7]}]
#set_property DRIVE 8 [get_ports {RAM_D[8]}]
#set_property DRIVE 8 [get_ports {RAM_D[9]}]
#set_property DRIVE 8 [get_ports {RAM_D[10]}]
#set_property DRIVE 8 [get_ports {RAM_D[11]}]
#set_property DRIVE 8 [get_ports {RAM_D[12]}]
#set_property DRIVE 8 [get_ports {RAM_D[13]}]
#set_property DRIVE 8 [get_ports {RAM_D[14]}]
#set_property DRIVE 8 [get_ports {RAM_D[15]}]

set_property SLEW FAST [get_ports {RAM_D[0]}]
set_property SLEW FAST [get_ports {RAM_D[1]}]
set_property SLEW FAST [get_ports {RAM_D[2]}]
set_property SLEW FAST [get_ports {RAM_D[3]}]
set_property SLEW FAST [get_ports {RAM_D[4]}]
set_property SLEW FAST [get_ports {RAM_D[5]}]
set_property SLEW FAST [get_ports {RAM_D[6]}]
set_property SLEW FAST [get_ports {RAM_D[7]}]
#set_property SLEW FAST [get_ports {RAM_D[8]}]
#set_property SLEW FAST [get_ports {RAM_D[9]}]
#set_property SLEW FAST [get_ports {RAM_D[10]}]
#set_property SLEW FAST [get_ports {RAM_D[11]}]
#set_property SLEW FAST [get_ports {RAM_D[12]}]
#set_property SLEW FAST [get_ports {RAM_D[13]}]
#set_property SLEW FAST [get_ports {RAM_D[14]}]
#set_property SLEW FAST [get_ports {RAM_D[15]}]

set_property PULLUP true [get_ports {RAM_D[0]}]
set_property PULLUP true [get_ports {RAM_D[1]}]
set_property PULLUP true [get_ports {RAM_D[2]}]
set_property PULLUP true [get_ports {RAM_D[3]}]
set_property PULLUP true [get_ports {RAM_D[4]}]
set_property PULLUP true [get_ports {RAM_D[5]}]
set_property PULLUP true [get_ports {RAM_D[6]}]
set_property PULLUP true [get_ports {RAM_D[7]}]
#set_property PULLUP true [get_ports {RAM_D[8]}]
#set_property PULLUP true [get_ports {RAM_D[9]}]
#set_property PULLUP true [get_ports {RAM_D[10]}]
#set_property PULLUP true [get_ports {RAM_D[11]}]
#set_property PULLUP true [get_ports {RAM_D[12]}]
#set_property PULLUP true [get_ports {RAM_D[13]}]
#set_property PULLUP true [get_ports {RAM_D[14]}]
#set_property PULLUP true [get_ports {RAM_D[15]}]

#set_property PACKAGE_PIN F5 [get_ports RAM_LB]
#set_property IOSTANDARD LVCMOS33 [get_ports RAM_LB]
#set_property PACKAGE_PIN E3 [get_ports RAM_UB]
#set_property IOSTANDARD LVCMOS33 [get_ports RAM_UB]

#set_property DRIVE 8 [get_ports {RAM_LB}]
#set_property DRIVE 8 [get_ports {RAM_UB}]
#set_property SLEW FAST [get_ports {RAM_LB}]
#set_property SLEW FAST [get_ports {RAM_UB}]

set_property PACKAGE_PIN n19 [get_ports RAM_CS]
set_property IOSTANDARD LVCMOS33 [get_ports RAM_CS]
set_property PACKAGE_PIN p19 [get_ports RAM_OE]
set_property IOSTANDARD LVCMOS33 [get_ports RAM_OE]
set_property PACKAGE_PIN R19 [get_ports RAM_WE]
set_property IOSTANDARD LVCMOS33 [get_ports RAM_WE]

set_property DRIVE 8 [get_ports {RAM_CS}]
set_property SLEW FAST [get_ports {RAM_CS}]
set_property DRIVE 8 [get_ports {RAM_OE}]
set_property SLEW FAST [get_ports {RAM_OE}]
set_property DRIVE 8 [get_ports {RAM_WE}]
set_property SLEW FAST [get_ports {RAM_WE}]

#// SD CARD //
set_property PACKAGE_PIN R3 [get_ports SD_CS]
#set_property PACKAGE_PIN K2 [get_ports SD_CS1]
set_property PACKAGE_PIN T1 [get_ports SD_MISO]
set_property PACKAGE_PIN T3 [get_ports SD_MOSI]
set_property PACKAGE_PIN R2 [get_ports SD_CLK]

set_property IOSTANDARD LVTTL [get_ports SD_CS]
set_property DRIVE 4 [get_ports SD_CS]
#set_property IOSTANDARD LVTTL [get_ports SD_CS1]
#set_property DRIVE 4 [get_ports SD_CS1]
set_property IOSTANDARD LVTTL [get_ports SD_MISO]
set_property PULLUP true [get_ports SD_MISO]
set_property IOSTANDARD LVTTL [get_ports SD_MOSI]
set_property DRIVE 4 [get_ports SD_MOSI]
set_property IOSTANDARD LVTTL [get_ports SD_CLK]
set_property DRIVE 4 [get_ports SD_CLK]
